server:
  port: 10010

spring:
  application:
    name: gateway


zuul:
  routes:
    user-service: /user/**
#  strip-prefix: true
#  prefix: /api
#  ignored-services:
#    - consumer-demo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10087/eureka, http://localhost:10086/eureka

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 16000

ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 5000

logging:
  level:
    com.yujizi: warn
